apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 15m
  targetNamespace: external-secrets
  chart:
    spec:
      chart: external-secrets
      version: "0.5.4"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
      # interval: 15m
  values:
    installCRDs: false
