apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: flux-system
spec:
  interval: 15m
  targetNamespace: grafana-cloud
  chart:
    spec:
      chart: kube-state-metrics
      version: ">=4.0.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      # interval: 15m
  values:
    image:
      tag: v2.4.2
